version: "2"
services:
  plone:
    image: plone:5
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.api.provides
    environment:
      ADDONS: "eea.api.provides[test]"
      DEVELOP: "src/eea.api.provides"
